version: '3'
services:
  jenkins:
    image: jenkins:jenkins-custom
    build : .
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"

volumes:
  jenkins_home:
